version: 2.1

parameters:
  ci_script:
    type: string
    default: "./build_steps/ci.sh"
  cd_script:
    type: string
    default: "./build_steps/cd.sh"

workflows:
  cicd_pipeline:
    jobs:
      - ci-pipeline
      - cd-pipeline:
          requires:
              - ci-pipeline

jobs:
  ci-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build utils and webapp docker images"
          command: << pipeline.parameters.ci_script >> build
      - run:
          name: "Run pre commit hooks (linting)"
          command: << pipeline.parameters.ci_script >> lint
      - run:
          name: "Run unit tests"
          command: << pipeline.parameters.ci_script >> unit_tests
      - run:
          name: "Start webapp container"
          command: << pipeline.parameters.ci_script >> up
      - run:
          name: "Stop webapp container"
          command: << pipeline.parameters.ci_script >> down
      - run:
          name: "Publish images to ACR"
          command: << pipeline.parameters.ci_script >> push_images
      - run:
          name: "Package Helm charts"
          command: << pipeline.parameters.ci_script >> helm_build
  cd-pipeline:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Install Helm chart to AWS cluster"
          command: << pipeline.parameters.cd_script >> helm_install
      - run:
          name: "Run helm test to ensure the application is up and running"
          command: << pipeline.parameters.cd_script >> helm_install
      # - run:
      #     name: "Uninstall Helm chart application"
      #     command: << pipeline.parameters.cd_script >> lint
