# yamllint disable-file
{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "aks-demo.fullname" . }}-ingress-service
  labels:
    {{- include "aks-demo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- with .Values.ingress }}
    - http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ tpl .service $ }}
              servicePort: {{ .port }}
      host: {{ tpl .host $ }}
  {{- end }}
{{- end }}
