# yamllint disable-file
{{- $aksDemoAppFullname := include "aks-demo.fullname" . -}}

{{- range .Values.global.aks_demo_secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $aksDemoAppFullname }}-{{ .name }}
type: Opaque
data:
{{- range $key, $value := .data -}}
{{ $key | nindent 2 }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
---
{{- end }}
