on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gbournique.azurecr.io
        username: ${{ secrets.acr_gbournique_username }}
        password: ${{ secrets.acr_gbournique_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "deployment/Dockerfile" -t gbournique.azurecr.io/aksdemocluster:${{ github.sha }} --label dockerfile-path=deployment/Dockerfile
        docker push gbournique.azurecr.io/aksdemocluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemocluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-playground | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-playground`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-playground
        container-registry-url: gbournique.azurecr.io
        container-registry-username: ${{ secrets.acr_gbournique_username }}
        container-registry-password: ${{ secrets.acr_gbournique_password }}
        secret-name: aksdemoclustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-playground
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          gbournique.azurecr.io/aksdemocluster:${{ github.sha }}
        imagepullsecrets: |
          aksdemoclustdockerauth
